name: Dagger Release Workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  dagger-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives the workflow permission to create releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'  # Update this to match the version in your go.mod and Dagger script

      - name: Install Dagger
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | sh
          sudo mv bin/dagger /usr/local/bin
          dagger version

      - name: Run Dagger workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd .github/dagger
          go mod tidy
          go mod download
          dagger run go run release.go
