name: Dagger Release Workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  dagger-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives the workflow permission to create releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      - name: Tidy modules
        run: go mod tidy

      - name: Run Dagger workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd .github/scripts
          go mod init dagger-release
          go mod edit -replace github.com/ssotops/gitspace-plugin=../..
          go get dagger.io/dagger@latest
          go mod tidy
          go run dagger-release.go
